### PR TITLE
Add mrfdev/CMI as a submodule to mrfdev/1mb

### LINKED ISSUE #11: [FEATURE] Add a git sub module to the mrfdev/CMI repository
**Script filename**
N/A

**Describe the feature you would like to see**
add a git submodule (basicly shows like a symlink in github, but cloning with --recursive (iirc) includes that repository too

**Additional context**
just makes it easier/ leaves it all in 1 place
https://git-scm.com/book/en/v2/Git-Tools-Submodules

### PR DESCRIPTION
**Pull request by the456gamer**
implements and closes #11

### CODE REVIEW

**Comment by the456gamer** [comment]
Discussed, no longer needed.

**Comment by mrfloris** [comment]
Just let me know when you think you've got it all set up and I have to click on a button :)
No rush.

**Comment by the456gamer** [comment]
Yeah been busy, will request review once I think it's done

**Comment by the456gamer** [comment]
i think i fast forwarded locally, and it worked? maybe it would have been fine

**Pull request merged**
